#!/bin/bash -e

cd "$(dirname "${BASH_SOURCE[0]}")"

temp_dir=$(mktemp -d /tmp/nvim-gdb-test-visual.XXXXXX)
export NVIM_LISTEN_ADDRESS=$temp_dir/sock

>visual.log

# Run the test suite with a visible neovim
./nvim -n --listen "$NVIM_LISTEN_ADDRESS" &

cleanup()
{
    kill -KILL "$(jobs -p)"
    wait
    reset
    cat visual.log
    rm -rf "$temp_dir"
}
trap cleanup EXIT

for _ in $(seq 0 10); do
    test -S "$NVIM_LISTEN_ADDRESS" && break
    sleep 0.1
done

./run "$@" >visual.log 2>&1
