#!/bin/bash -e

cd "$(dirname "${BASH_SOURCE[0]}")"

temp_dir=$(mktemp -d nvim-gdb-test.XXXXXX)
export NVIM_LISTEN_ADDRESS=$temp_dir/sock

>visual.log

# Run the test suite with a visible neovim
LANG=en_US.UTF-8 nvim -n -u init.vim --listen "$NVIM_LISTEN_ADDRESS" &

cleanup()
{
    kill -KILL "$(jobs -p)"
    wait
    reset
    cat visual.log
    rm -rf "$temp_dir"
}
trap cleanup EXIT

for i in $(seq 0 10); do
    test -S "$NVIM_LISTEN_ADDRESS" && break
    sleep 0.1
done

./run "$@" >visual.log 2>&1
